### PR TITLE
Add `Rootstock` chain

### PR DESCRIPTION
**Pull request by ahsan-javaiid**
## Description
This PR adds `Rootstock` chain support to smart-order-router. Previously `Rootstock` is added and released under https://github.com/Uniswap/sdk-core as Uniswap v3 contracts deployed to Rootstock.

## Reference:
https://github.com/Uniswap/sdk-core/pull/123

### CODE REVIEW

**Comment by jsy1218** [comment]
@ahsan-javaiid there's some genuine error, sourced from Unit Tests:

> 0x6B1a73d547F4009A26B8485b63D7015D248AD406 is not a valid address.
> 
>       658 |
>       659 | // Rootstock Tokens
>     > 660 | export const DAI_ROOTSTOCK = new Token(
>           |                              ^
>       661 |   ChainId.ROOTSTOCK,
>       662 |   '0x6B1a73d547F4009A26B8485b63D7015D248AD406',
>       663 |   18,
> 
>       at validateAndParseAddress (node_modules/@uniswap/sdk-core/src/utils/validateAndParseAddress.ts:11:11)
>       at new Token (node_modules/@uniswap/sdk-core/src/entities/token.ts:51:[22](https://github.com/Uniswap/smart-order-router/actions/runs/8322756751/job/22797361015?pr=516#step:7:23))
>       at Object.<anonymous> (src/providers/token-provider.ts:660:[30](https://github.com/Uniswap/smart-order-router/actions/runs/8322756751/job/22797361015?pr=516#step:7:31))
>       at Object.<anonymous> (src/providers/caching-token-provider.ts:7:1)

Don't worry about Integration Tests failure, as you don't have the JSON RPC URLs in your forked repo. However Unit Tests are self-contained, and should be able to pass.

**Comment by jsy1218** [comment]
Couple things needed:

1. caching-token-provider need to add RootStock: https://github.com/Uniswap/smart-order-router/pull/511/files#diff-615bf7538df0e457fdd95bd9c65eacf3c0ff3bb1c410f7ba1162927a8e9e4e79
2. v2 and v3 static-subgraph-provider need to add popular token for pool, as there's no subgraph for rootstock uniswap yet: https://github.com/Uniswap/smart-order-router/pull/511/files#diff-d6f60d0c4cf75c24903811d5018b7c23ab3d14d86008fbfa4adf2c1b787e76a9 & https://github.com/Uniswap/smart-order-router/pull/511/files#diff-f2269751335f6c3d2caa210ea406dff2fb2d0a22f6295296fa7d53124afbaf82
3. v3 gas-costs need to include rootstock: https://github.com/Uniswap/smart-order-router/pull/511/files#diff-585c7f0b7e0175f0224fdc2d3cd6d5d2182bae26c80ca294b26bf97b4c8f818a
4. Remove Rootstock from WETH9 exclusion https://github.com/Uniswap/smart-order-router/pull/511/files#diff-ae0915db441ef04255b5004a12525a8d227e8e6ef124e754d896142e179198e2.
5. WRAPPED_NATIVE_CURRENCY needs to add RBTC

Also is it true that RBTC is the native currency on Rootstock, used for paying gas etc.? If that's true, then for 1-4, RBTC will need to be added into the token lists as well.

I'm slightly uncertain about routing for bitcoin side chain, since Rootstock will be the first non-ethereum side chain we support. Would be great if the integ-test can be added as well https://github.com/Uniswap/smart-order-router/pull/511/files#diff-b1a09e5a7156f19225eba6ca4e2e78d0942580ff1118bab472bf0ea3b1294904. I can help run the integration test on my local to ensure the routing on rootstock works.

**Comment by ahsan-javaiid** [comment]
@jsy1218 
Thinking a work around to update this pull request without graph/subgraph endpoint which is under development. Just asking if i can add subgraph later keeping it as todo for now. 🤔

**Comment by jsy1218** [comment]
> @jsy1218 
> Thinking a work around to update this pull request without graph/subgraph endpoint which is under development. Just asking if i can add subgraph later keeping it as todo for now. 🤔 

You can use the static subgraph provider class to work around. However I realized that our external providers don't support RootStock yet, which means token balances, staticcall RPC calls (e.g. multicall) won't be available in routing yet.

**Comment by ahsan-javaiid** [comment]
> > @jsy1218
> > Thinking a work around to update this pull request without graph/subgraph endpoint which is under development. Just asking if i can add subgraph later keeping it as todo for now. 🤔
> 
> You can use the static subgraph provider class to work around. However I realized that our external providers don't support RootStock yet, which means token balances, staticcall RPC calls (e.g. multicall) won't be available in routing yet.

@jsy1218 Would be great to know which external providers are required for routing here. ？ Thanks

**Pull request closed without merging**
