### PR TITLE
Add base sepolia addresses

### PR DESCRIPTION
**Pull request by danielcrt**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add support for Base Sepolia using the addresses from this PR: https://github.com/Uniswap/sdk-core/pull/110

- **What is the current behavior?** (You can also link to an open issue here)
No support for Base Sepolia

- **What is the new behavior (if this is a feature change)?**
Support Base Sepolia ulticall. 

- **Other information**:

### CODE REVIEW

**Comment by jsy1218** [comment]
There was a BASE_GOERLI [PR](https://github.com/Uniswap/smart-order-router/pull/472#issuecomment-1889678091), that was closed due to not sufficient LP liquidities. Can you add LP liquidities on BASE_SEPOLIA?

**Comment by danielcrt** [comment]
@jsy1218 I saw there's also no liquidity on Ethereum Sepolia for ETH/[USDC](https://sepolia.etherscan.io/address/0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238)

What would be the min requirements to move this forward? 
Is 1 ETH/USDC (0.3%) LP on Base Sepolia enough or do I have to create multiple tiers?
What's the min liquidity I have to provide?

I can create a ETH/USDC pool on Base Sepolia with ~100 ETH / 100 USDC.

**Comment by jsy1218** [comment]
> @jsy1218 I saw there's also no liquidity on Ethereum Sepolia for ETH/[USDC](https://sepolia.etherscan.io/address/0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238)
> 
> What would be the min requirements to move this forward? Is 1 ETH/USDC (0.3%) LP on Base Sepolia enough or do I have to create multiple tiers? What's the min liquidity I have to provide?
> 
> I can create a ETH/USDC pool on Base Sepolia with ~100 ETH / 100 USDC.

~0.1 ETH / 300 USDC should be good enough. A single fee tier should be fine, I would create 0.05% instead of 0.3%, since 0.05% WETH/USDC is the most popular fee-tier pool on v3 L1.

**Comment by danielcrt** [comment]
> > @jsy1218 I saw there's also no liquidity on Ethereum Sepolia for ETH/[USDC](https://sepolia.etherscan.io/address/0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238)
> > What would be the min requirements to move this forward? Is 1 ETH/USDC (0.3%) LP on Base Sepolia enough or do I have to create multiple tiers? What's the min liquidity I have to provide?
> > I can create a ETH/USDC pool on Base Sepolia with ~100 ETH / 100 USDC.
> 
> ~0.1 ETH / 300 USDC should be good enough. A single fee tier should be fine, I would create 0.05% instead of 0.3%, since 0.05% WETH/USDC is the most popular fee-tier pool on v3 L1.

I saw the pool is already initialized: https://sepolia.basescan.org/address/0x94bfc0574FF48E92cE43d495376C477B1d0EEeC0

What would be the best (easiest) way to add liquidity? Via a smart contract / basescan?

**Comment by danielcrt** [comment]
I saw the WETH/USDC pool is already initialized: https://sepolia.basescan.org/address/0x94bfc0574ff48e92ce43d495376c477b1d0eeec0
But with a very bad ratio: 
0.000000000000000001 WETH 
0.900001 USDC

I tried to mint a new position and add liquidity in order to balance the pool but without success. Can you please guide me how to fix this imbalance? Or what other solution can I work towards?

**Pull request closed without merging**
