### PR TITLE
fix: ticks crossing gas estimate

### PR DESCRIPTION
**Pull request by jsy1218**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

- **What is the current behavior?** (You can also link to an open issue here)
We have incorrect tick crossing gas estimate logic

- **What is the new behavior (if this is a feature change)?**
We are fixing tick crossing gas estimate logic. This is relevant for v3 and mixed (v3 part of mixed)

- **Other information**:

### CODE REVIEW

**Comment by jsy1218** [comment]
* **#673** <a href="https://app.graphite.dev/github/pr/Uniswap/smart-order-router/673?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jsy1218 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cgkol — COMMENTED** [review]
Shall we add some tests? also in prod, how will we verify that it works?

**Comment by xrsv** [comment]
curious how did we figure out that gas estimation logic was incorrect? 
do you think division by zero error could be related?

**Comment by jsy1218** [comment]
> Shall we add some tests? also in prod, how will we verify that it works?
> 

yes on adding tests. I do think it's a bit difficult to verify it's fully working in prod, because SOR gas estimate has been knowingly off. Better way is to let the quoter returns a somewhat accurate gas estimate, and SOR just uses it in the gas model classes.

**Comment by jsy1218** [comment]
> curious how did we figure out that gas estimation logic was incorrect? 
> do you think division by zero error could be related?

@xrsv and I chatted offline. It's a combination of discussing with protocol team, as well as reading the pool swap contract. Division by zero is prob due to some other reason, my guess is because the quote amount is too small getting close to zero.

**Review by xrsv — APPROVED** [review]

**Pull request merged**
