### PR TITLE
Add Arbitrum Goerli

### PR DESCRIPTION
**Pull request by gzeoneth**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR add support for Arbitrum Goerli Testnet (chainId: 421613)

- **What is the current behavior?** (You can also link to an open issue here)

`smart-order-router` currently does not support Arbitrum Goerli

- **What is the new behavior (if this is a feature change)?**

`smart-order-router` will support Arbitrum Goerli

- **Other information**:

The Arbitrum Team have deployed an instance of Uniswap V3 on Arbitrum Goerli as follow
```
const ARBITRUM_GOERLI_V3_CORE_FACTORY_ADDRESSES = '0x4893376342d5D7b3e31d4184c08b265e5aB2A3f6'
const ARBITRUM_GOERLI_ROUTER_ADDRESS = '0xab7664500b19a7a2362Ab26081e6DfB971B6F1B0'
const ARBITRUM_GOERLI_V3_MIGRATOR_ADDRESSES = '0xA815919D2584Ac3F76ea9CB62E6Fd40a43BCe0C3'
const ARBITRUM_GOERLI_MULTICALL_ADDRESS = '0x8260CB40247290317a4c062F3542622367F206Ee'
const ARBITRUM_GOERLI_QUOTER_ADDRESSES = '0x1dd92b83591781D0C6d98d07391eea4b9a6008FA'
const ARBITRUM_GOERLI_NONFUNGIBLE_POSITION_MANAGER_ADDRESSES = '0x622e4726a167799826d1E1D150b076A7725f5D81'
const ARBITRUM_GOERLI_TICK_LENS_ADDRESSES = '0xb52429333da969a0C79a60930a4Bf0020E5D1DE8'
```

This PR will unblock the integration to `uniswap-interface`

### CODE REVIEW

**Comment by gzeoneth** [comment]
https://github.com/Uniswap/interface/pull/5457 blocked on this, any update?

**Review by snreynolds — APPROVED** [review]
lgtm!

**Review by willpote — APPROVED** [review]

**Comment by willpote** [comment]
@gzeoneth just need the merge conflict addressed then can merge

**Comment by gzeoneth** [comment]
> @gzeoneth just need the merge conflict addressed then can merge

resolved

**Comment by gzeoneth** [comment]
can we release this?

**Pull request merged**
