### PR TITLE
feat: implement v4 subgraph provider

### PR DESCRIPTION
**Pull request by jsy1218**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature 

- **What is the current behavior?** (You can also link to an open issue here)
We don't have subgraph provider for v4

- **What is the new behavior (if this is a feature change)?**
We will implement the initial subgraph provider for v4.

- **Other information**:
There's an initially deployed v4 subgraph on sepolia. We'd be able to use that subgraph for initial testing.

### CODE REVIEW

**Comment by jsy1218** [comment]
* **#655** <a href="https://app.graphite.dev/github/pr/Uniswap/smart-order-router/655?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jsy1218 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by cgkol — COMMENTED** [review]
This looks almost  the same with v3, are there any differences? If not, shall we consider creating some common classes? wdyt?

**Comment by jsy1218** [comment]
> This looks almost  the same with v3, are there any differences? If not, shall we consider creating some common classes? wdyt?

I actually thought about it. I can see merits in refactoring vs separation to begin with. The main benefit about separation is that if we make changes in v4 subgraph, it's easier to make changes in only a single class. One immediate thing I can see we need to change is to fetch the sqrtPriceX96 and tick, which wasn't needed in v3 subgraph.

**Review by xrsv — APPROVED** [review]
nice!

**Pull request merged**
